css/my-card.css
Contrast color issues are fixed now. 
The Component meet AA level at least.
=> #3 fix: resolve wcag 2.1 audit, change contrast colors to meet AAA Level

.prettierignore, README.md, babel.config.js, package-lock.json, package.json, rollup.config.js, src/my-card.js, static/css/my-card.css, static/i18n/en-US/messages.json, static/i18n/es-ES/messages.json, static/i18n/fr-FR/messages.json, static/i18n/jsonschema.json, static/i18n/nl-NL/messages.json
https://prettier.io auto formats code is a consistent way.
https://prettier.io/docs/en/options.html and can be configured if you have differing style preferences.
=> style: add prettier formatter

.travis.yml
https://docs.travis-ci.com/user/tutorial
Example result: https://travis-ci.com/ChristianMurphy/CardWebComponents/builds/90165592
=> ci: setup travis continuous integration testing

README.md, src/my-card.js, static/index.html
define `static get observeredAttributes` only once.
update and re-render component when attribute changed callback runs.
extract urlMessages function.
use async await for network calls.
=> style: resolve eslint warnings

package-lock.json, src/my-card.js
Now the menu works well with keyboard tab key
=> fix: aria-expanded toggle with true and false

src/my-card.js
resolve #14 
following [wai-aria-practices menu-button](https://www.w3.org/TR/wai-aria-practices/examples/menu-button/menu-button-actions.html)
=> a11y: add aria roles & aria-haspopup on menu

README.md
=> doc: update README and add i18n screenshot

static/i18n/en-US/messages.json, static/i18n/es-ES/messages.json, static/i18n/fr-FR/messages.json, static/i18n/nl-NL/messages.json
=> fix: security noopener

package-lock.json, package.json, rollup.config.js, static/index.html
- make use of resource-hint
- minify JS
=> fix: improve performances on mobile 3G

README.md
=> doc: update Readme to have the webcomponent in uPortal5

README.md, package-lock.json, package.json, src/my-card.js, static/css/my-card.css, static/i18n/en-US/messages.json, static/i18n/es-ES/messages.json, static/i18n/fr-FR/messages.json, static/i18n/nl-NL/messages.json
To solve multiple versions of fontawesome conflicts in uPortal (see: #28), the component use only fontawesome svg directly (it don't use fontawesome css/js libs)
- add fontawesome dependancies
- change Readme
- performance improvements : x2.5 faster in rendering
=> fix: resolve font conflicts + improve performance

README.md, src/my-card.js, static/i18n/it/messages.json
=> i18n: add italian support

static/i18n/en-US/messages.json, static/i18n/fr-FR/messages.json
fix spellings in english and french... 😊 
=> messages: fix spellings in en and fr

README.md
update of readme and add a new screencapture
=> doc: update README and screencapture

package-lock.json, package.json, static/css/my-card.css, static/scss/my-card.scss
=> feat: adopt sass

static/css/my-card.css, static/scss/my-card.scss
Styles are scoped and improved, tested locally on FF, Chrome, Edge.
=> style: improvements in .scss

static/css/my-card.css, static/scss/my-card.scss
see issue comments... resolve #49 
=> style: fix first letter typography and first line

static/i18n/jsonschema.json
=> data: update jsonSchema

static/scss/my-card.scss
removed some duplicated rules.
merged similar selectors into groups.
=> style: minor cleanup

COMMITTERS.md
=> docs: add project lead and committers information to repo

.stylelintrc.yaml, package-lock.json, package.json, static/scss/my-card.scss
=> style: add stylelint validation for scss

static/i18n/jsonschema.json
update json schema with the i18n toggle menu label ( see #62 )
=> fix: update json schema with toggle i18n states labels

src/my-card.js
=> fix: remove trailing idref

src/my-card.js, static/i18n/zn-CN/messages.json, static/index_zn-CN.html, static/scss/my-card.scss
Add support for Simplified Chinese  (Thanks Wei 🎉 )
=> i18n + feat: Add Support for Simplified Chinese zn-CN

README.md
Documentation : 
update links in readme and remove all references to https://cousquer.github.io
=> doc: update uportal-contrib links in readme

package-lock.json, package.json
update to hyperHTML 2.25.2
tested locally and remotely (automated testing + manual testing) -> it works as expected ✅ 
=> build: update to hyperHTML 2.25.2

static/scss/my-card.scss
=> style(i18n): resolve animation bug in Edge in Standard Arabic

static/index_albatros.html, static/index_grid-labs.html, static/scss/my-card.scss
=> fix(style + a11y): provide layouts examples in CSS flex and CSS Grid

.github/PULL_REQUEST_TEMPLATE.md, package-lock.json, package.json, renovate.json
This updates the node modules and the package lock file to ensure no insecure sub-dependencies are included.
[individual contributor license agreement]: https://www.apereo.org/licensing/agreements/icla 
=> chore: update dependencies and lockfile

.github/workflows/CI.yml, .travis.yml, README.md
Adds cross platform continuous integration
[individual contributor license agreement]: https://www.apereo.org/licensing/agreements/icla
=> ci: remove unused travis ci config, add github actions ci

package-lock.json, package.json, src/my-card.js
[individual contributor license agreement]: https://www.apereo.org/licensing/agreements/icla
=> build: support node 13

.github/workflows/CI.yml
[individual contributor license agreement]: https://www.apereo.org/licensing/agreements/icla
=> ci: run rollup build

src/my-card.js
there were a little Accessibility issue raised by Axe-core, this pull-request resolved it
[individual contributor license agreement]: https://www.apereo.org/licensing/agreements/icla
=> Fix(a11y): add aria-busy on menu
